### ISSUE TITLE
Is there a way to customize login success html page?

### ISSUE THREAD

**Issue by flashmandv** [hippogamesunity/SimpleGoogleSignIn#1]
So your Google login plugin works great and is well documented and big thank you for your work!

But I want to be able to customize the Desktop login success message.
Is there a way to do that? Right now is simple text saying "Success! Please close the browser tab and return to <GAMENAME>"

Thank you!

**Comment by hippogamesunity** [comment]
Hi, GoogleAuth.cs line 60.
