### ISSUE TITLE
Getting "Access Blocked: hippogames.dev has not completed the Google verification process" when trying to sign-in with google

### ISSUE THREAD

**Issue by katsub** [hippogamesunity/SimpleGoogleSignIn#10]
Hello,

I've uploaded my app to itch.io and tested google sign-in, it works fine from Chrome on Windows, however I sent it for a friend to test and he's getting error "Access Blocked: hippogames.dev has not completed the Google verification process" when trying to sign-in with google (also from Chrome on Windows, but with his account).

When will this be fixed?

**Comment by hippogamesunity** [comment]
Hello, do you request extra scopes? Can you capture a video of your
complete setup? (Google Cloud, Unity, itch). I also need your itch link.

пт, 15 дек. 2023 г., 02:53 katsub ***@***.***>:

**Comment by katsub** [comment]
Hello,

I've managed to fix it by adding the client id / secret of a new oauth scope to desktop, and doing a clean build. This is confusing to me because I'm in a webgl build (literally running on chrome), so I'm not sure exactly why or how it was fixed, but for now I'm taking that solution

**Comment by hippogamesunity** [comment]
Great! Read manuals carefully. The wiki clearly states that you need Client Secret for WebGL. Good luck, and hope to get your review on the Asset Store.
