### ISSUE TITLE
Login on App Start

### ISSUE THREAD

**Issue by malishabg** [hippogamesunity/SimpleGoogleSignIn#11]
Is it possible to make automatical login on App Start? I tried to call the function SignIn from the script on App start and I got the error message:

NullReferenceException: Object reference not set to an instance of an object
Assets.SimpleGoogleSignIn.Profile.SignIn () (at Assets/Scripts/Profile.cs:25)

**Comment by hippogamesunity** [comment]
Hello! The current asset version doesn't contain Profile.cs. This is probably your game part.

**Comment by hippogamesunity** [comment]
Remove the asset and import the latest version from the Asset Store.
If the asset was modified, I can't provide support in this case.

**Comment by malishabg** [comment]
I bought the asset a few days ago so it's the latest version, and I just created a new script Profile.cs and copied the code from Example.cs, nothing else changed. But I am calling the function from another script with GetComponent<Profile>().SignIn(); Maybe this is the wrong way to call this function?

**Comment by hippogamesunity** [comment]
The asset should work in Start, I don't see any reasons why not.
Debug your code and find what variable is NULL, then find a reason why it's NULL.

**Comment by malishabg** [comment]
I just want to call the function on Start, to avoid clicking on the button to Sign in every time I enter the APP. I think you should have that option by default.. it's throwing Null at

        public void SignIn()
        {
            GoogleAuth.SignIn(OnSignIn, caching: true);
        }

**Comment by Gurwar** [comment]
I'm trying to do the same thing, automatically logon to the application without input from the user (as long as they already signed in on the same device successfully). Unfortunately I am getting a null reference for GoogleAuth.TokenResponse and GoogleAuth.TokenResponse.IdToken which I need. I am however getting the correct data for userData.name and email.

**Comment by hippogamesunity** [comment]
Hi, I'll check this soon.

**Comment by hippogamesunity** [comment]
Hello! I can confirm that the latest version support signing in inside the Start()
![image](https://github.com/hippogamesunity/SimpleGoogleSignIn/assets/7318172/719f3ade-96e7-48df-9e86-1a03f437e514)

**Comment by hippogamesunity** [comment]
GoogleAuth.TryResume added in 3.7
