### ISSUE TITLE
Error: 'GoogleSignIn/GIDSignIn.h' file not found

### ISSUE THREAD

**Issue by cimved** [hippogamesunity/SimpleGoogleSignIn#12]
When I try to build the app on Xcode, I get this error:

`'GoogleSignIn/GIDSignIn.h' file not found`

I am using the latest version 3.6. Any ideas how to solve this?

Xcode version: 14.3.1
Unity Version: 2022.3.5f1

**Comment by hippogamesunity** [comment]
Hi, the error probably relates to native google sign in. My asset doesn't use this file, as any native plugins.

**Comment by cimved** [comment]
Hi @hippogamesunity 

Thanks for the quick response. You're right. I was replacing an old Google Sign-in plugin with yours and forgot to delete some files. I've deleted them and it now works. Thanks.
