### ISSUE TITLE
GoogleAuth - UserCancelledHook

### ISSUE THREAD

**Issue by EgilKav** [hippogamesunity/SimpleGoogleSignIn#13]
Hey there, if you coud tweak the package to make the UserCancelledHook use UnscaledTime instead of Time in the GoogleAuth class, that would be great. 

In situations where my time scale is set to 0, such as when the user is navigating a menu, this configuration impedes the callback from triggering until I exit the menu.

Kind regards Egil

**Comment by hippogamesunity** [comment]
Implemented in 3.7
