### ISSUE TITLE
Application cant open again

### ISSUE THREAD

**Issue by Aryan001021** [hippogamesunity/SimpleGoogleSignIn#15]
using dependencies (netcode for gameobject , gltfast) 
1.In first bootup ,I can sign in but after sign out when i try to sign in again ( It logs user cancelled).
2. Next time I try to open the build it crashed on start

https://github.com/hippogamesunity/SimpleGoogleSignIn/assets/115328269/b7f838f8-975a-4fd7-af5d-872539841894

**Comment by hippogamesunity** [comment]
Thanks for making a video, fixed in v3.8!

**Comment by Aryan001021** [comment]
> Thanks for making a video, fixed in v3.8!

Also I always get script updating consent every time scripts get compile , if i say yes , the package stop working, Can you tell how to resolve this too ,thanks

**Comment by hippogamesunity** [comment]
The package is available on the Asset Store, get it as usual.

чт, 7 мар. 2024 г., 10:13 Aryan001021 ***@***.***>:
