### ISSUE TITLE
Unity version confirm

### ISSUE THREAD

**Issue by chiangandy** [hippogamesunity/SimpleGoogleSignIn#16]
I saw your Unity asset store said origin unity version is "2021.3.35 or higher", since my project is developing in 2021.3.30f1. Is it ok to use your plugin?

**Comment by hippogamesunity** [comment]
Hello, yes!

**Comment by ekdrnqkdrn** [comment]
Hello. Is the plugin available in Unity version 2021.3.23f1?

**Comment by hippogamesunity** [comment]
Yes, it will work with any Unity 2021.
