### ISSUE TITLE
Unable to process request (WebGL)

### ISSUE THREAD

**Issue by Oaiciii** [hippogamesunity/SimpleGoogleSignIn#3]
I'm using google sign in for a webGL application, after I click sign in, I'm redirected on google sign in to choose with which account I log in, after a log in with the account I receive this errore 

"Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared."

**Comment by hippogamesunity** [comment]
Hello, please update the asset and check Wiki for WebGL setup steps.

**Comment by hippogamesunity** [comment]
Please let me know if it works for you now @Oaiciii

**Comment by Oaiciii** [comment]
thank you for the answer!
As soon I will update and try, I will let you know if now everything's works

**Comment by Oaiciii** [comment]
sorry for the delay, I keep having the same problem, I'm using firebase for the redirect uri, this is my first time authenticating and it's possible I'm doing something wrong

**Comment by hippogamesunity** [comment]
For WebGL, Redirect URI should be Authorisation Middleware, not Firebase. Please refer to Wiki, there are detailed steps for WebGL.

**Comment by hippogamesunity** [comment]
Basically, you can just create a new project in Unity, import the asset, then switch to WebGL and press Build&Run. This will work.

**Comment by Oaiciii** [comment]
Oh ok, thank you so much for your help!!
