### ISSUE TITLE
First attempt of GoogleSignIn fails with weird behavior on iOS

### ISSUE THREAD

**Issue by Trunksome** [hippogamesunity/SimpleGoogleSignIn#7]
Hi there!

I implemented the plugin with the latest version (FYI would be great to put the current version into the readme file, maybe with change notes!) and it works great on Android.

On my iPhone (running iOS 17.0.3), the sign in first shows this loading spinner for quite a while:
![image](https://github.com/hippogamesunity/SimpleGoogleSignIn/assets/16858868/d0029fb1-365d-4938-a3d1-37e4e3e2a15a)

... and then finally just shows me the google homepage (excuse the German):
![image](https://github.com/hippogamesunity/SimpleGoogleSignIn/assets/16858868/6fcc33d7-1e6b-4840-b4cf-92bd5b8a60c5)

I need to click on done, the SignIn has neither succeeded nor failed; and I need to click on SignIn again. This time, it works -> automatically closes the browser and returns to the app like expected.

I have "Use Safari View Controller" set to true. Have you seen this behavior before? Is there something wrong with my implementation?
Hope you can help me improve this, its not an ideal UX that's for sure.

**Comment by hippogamesunity** [comment]
Hello! Please install Pixel Studio from the App Store and press Google Drive from the main menu. Will my app behave the same way on your device? I also use this plugin in my app.

**Comment by hippogamesunity** [comment]
Nobody has reported about this issue honestly.

**Comment by Trunksome** [comment]
> Hello! Please install Pixel Studio from the App Store and press Google Drive from the main menu. Will my app behave the same way on your device? I also use this plugin in my app.

I just did! Pretty much the same behavior.
This is the flow:
![image](https://github.com/hippogamesunity/SimpleGoogleSignIn/assets/16858868/02970a31-8909-442d-a504-79091ae792aa)

![photo_2023-11-22_17-30-39](https://github.com/hippogamesunity/SimpleGoogleSignIn/assets/16858868/62165cab-9913-4d8c-ba51-3e186523d612)

... then i go into Gmail via the notification to complete the 2-factor-auth ...
In this case, give google drive permissions...

![photo_2023-11-22_17-30-40](https://github.com/hippogamesunity/SimpleGoogleSignIn/assets/16858868/b8ed64eb-702b-45ef-b5e1-a679f2654cd8)

and then end up on the search page. I then press done to return to your app...

![image](https://github.com/hippogamesunity/SimpleGoogleSignIn/assets/16858868/29f3ed96-05ac-467b-8e09-23cbd52f04e8)

... and i get no cancel error.

**Comment by hippogamesunity** [comment]
Thanks for letting me know, I'll try to investigate this issue.

**Comment by Trunksome** [comment]
> Thanks for letting me know, I'll try to investigate this issue.

Thank you! Great response time, appreciated.

Sidenote: I signed up to the Upwork mobile app today, did the Google login there, and how it worked there was a login page that was only covering 3/4 of the screen, coming from the bottom somehow. Very smooth and fast, and I think no 2 factor necessary. I wonder what the difference is here, im guessing a more native approach?

**Comment by hippogamesunity** [comment]
Google has native plugins for different platforms, much complicated setup compared to oauth 2.0 (web).

**Comment by hippogamesunity** [comment]
What are your steps to reproduce the issue? Considering I'm already authorized with the asset.

**Comment by hippogamesunity** [comment]
Please also attach logs from xcode.

**Comment by hippogamesunity** [comment]
Fixed in 3.3. Please let me know if it's fine now.

**Comment by Trunksome** [comment]
Oh wow! What was the issue? Ill try it soon 👍

**Comment by hippogamesunity** [comment]
The issue was that FaceId takes focus and then activates the app. The app thinks user has closed the auth screen with no auth.

**Comment by Trunksome** [comment]
just tried it, seems to work now! Thank you, amazingly fast fix.

**Comment by hippogamesunity** [comment]
Great, hope to get your review!
