### ISSUE TITLE
Suggestion: Manual user cancellation.

### ISSUE THREAD

**Issue by maxgmer** [hippogamesunity/SimpleGoogleSignIn#9]
Right now, the way sign-in works is when the user goes back to the game without finishing the sign-in flow, it is considered as cancellation.

In rare cases, when the internet connection is bad + the player is impatient, this case can happen:
1. User starts sign-in flow.
2. User enters google email, password and presses "Enter".
3. Without waiting for the google auth to finish, the player goes back to the app.

If the connection is bad, success redirection might not come soon enough and the game will consider the flow as cancelled (due to `OnApplicationFocus()`).
Then, the success redirect will come, but logs will just say "Unexpected deep link", as the library already thinks the user cancelled the flow.

Suggestion:

1. Add "manualUserCancellationHandling" bool into GoogleAuthSettings.
2. Make "UserCancelledHook" method public.
3. Wrap all `ApplicationFocusHook.Create(UserCancelledHook);` like this:
```
 if (!manualUserCancellationHandling)
{
    ApplicationFocusHook.Create(UserCancelledHook);
}
```

Then, we will just set `manualUserCancellationHandling: true` and call `UserCancelledHook()` from our side for custom cancellation logic.

**Comment by hippogamesunity** [comment]
Hi, implemented in v3.5
https://github.com/hippogamesunity/SimpleGoogleSignIn/wiki/Manual-cancellation

Please let me know if it works for you now.

**Comment by maxgmer** [comment]
@hippogamesunity Oh, so quick! Thank you!
Yes, works perfectly.
Is it safe to call Cancel() multiple times in a row? Will it have the same effect as calling it once? Or should we make sure Cancel() is called once and only when a deep link is expected?

**Comment by hippogamesunity** [comment]
1 call is enough, next calls do the same.

вс, 10 дек. 2023 г., 20:44 Maksim Hapeyenka ***@***.***>:

**Comment by maxgmer** [comment]
Thanks!
